[build]
publish = "dist/control-ui"
command = "npm --prefix /Users/8bit/Downloads/nanosolana/ui ci && npm --prefix /Users/8bit/Downloads/nanosolana/ui run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
