import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-nanoclawd writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.nanoclawd.mac"
let gatewayLaunchdLabel = "ai.nanoclawd.gateway"
let onboardingVersionKey = "nanoclawd.onboardingVersion"
let onboardingSeenKey = "nanoclawd.onboardingSeen"
let currentOnboardingVersion = 7
let pauseDefaultsKey = "nanoclawd.pauseEnabled"
let iconAnimationsEnabledKey = "nanoclawd.iconAnimationsEnabled"
let swabbleEnabledKey = "nanoclawd.swabbleEnabled"
let swabbleTriggersKey = "nanoclawd.swabbleTriggers"
let voiceWakeTriggerChimeKey = "nanoclawd.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "nanoclawd.voiceWakeSendChime"
let showDockIconKey = "nanoclawd.showDockIcon"
let defaultVoiceWakeTriggers = ["nanoclawd"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "nanoclawd.voiceWakeMicID"
let voiceWakeMicNameKey = "nanoclawd.voiceWakeMicName"
let voiceWakeLocaleKey = "nanoclawd.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "nanoclawd.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "nanoclawd.voicePushToTalkEnabled"
let talkEnabledKey = "nanoclawd.talkEnabled"
let iconOverrideKey = "nanoclawd.iconOverride"
let connectionModeKey = "nanoclawd.connectionMode"
let remoteTargetKey = "nanoclawd.remoteTarget"
let remoteIdentityKey = "nanoclawd.remoteIdentity"
let remoteProjectRootKey = "nanoclawd.remoteProjectRoot"
let remoteCliPathKey = "nanoclawd.remoteCliPath"
let nanoSolanaGatewayURLKey = "nanoclawd.nanoSolana.gatewayUrl"
let nanoSolanaGatewaySecretKey = "nanoclawd.nanoSolana.gatewaySecret"
let nanoSolanaDefaultGatewayURL = "http://127.0.0.1:18790"
let canvasEnabledKey = "nanoclawd.canvasEnabled"
let cameraEnabledKey = "nanoclawd.cameraEnabled"
let systemRunPolicyKey = "nanoclawd.systemRunPolicy"
let systemRunAllowlistKey = "nanoclawd.systemRunAllowlist"
let systemRunEnabledKey = "nanoclawd.systemRunEnabled"
let locationModeKey = "nanoclawd.locationMode"
let locationPreciseKey = "nanoclawd.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "nanoclawd.peekabooBridgeEnabled"
let deepLinkKeyKey = "nanoclawd.deepLinkKey"
let modelCatalogPathKey = "nanoclawd.modelCatalogPath"
let modelCatalogReloadKey = "nanoclawd.modelCatalogReload"
let cliInstallPromptedVersionKey = "nanoclawd.cliInstallPromptedVersion"
let heartbeatsEnabledKey = "nanoclawd.heartbeatsEnabled"
let debugPaneEnabledKey = "nanoclawd.debugPaneEnabled"
let debugFileLogEnabledKey = "nanoclawd.debug.fileLogEnabled"
let appLogLevelKey = "nanoclawd.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
